---
- hosts: all
  become: yes
  become_method: sudo

  pre_tasks:
  - name: update package information
    apt: name=software-properties-common state=latest update_cache=yes

  - name: add new GPG key
    apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

  - name: add docker repo
    apt_repository: repo={{ xenial_repo }} state=present

  - name: install docker
    apt: name={{ item }} state=present update_cache=yes install_recommends=yes
    with_items:
      - docker-engine
      - python-pip

  - name: install docker-compose
    pip:  name=docker-compose

  tasks:
    - include: user_creation.yml
    - include: app_configuration.yml
    - include: app_launch.yml
